CREATE TABLE categorias (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL UNIQUE,
    descripcion VARCHAR2(255),
    estado NUMBER(1) DEFAULT 1 -- 1 = TRUE, 0 = FALSE
);

CREATE TABLE productos (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(255),
    id_categoria NUMBER NOT NULL,
    precio_compra NUMBER(10,2) NOT NULL,
    precio_venta NUMBER(10,2) NOT NULL,
    stock_minimo NUMBER DEFAULT 0,
    estado NUMBER(1) DEFAULT 1,
    CONSTRAINT fk_categoria FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria)
);

CREATE TABLE proveedores (
    id_proveedor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    contacto VARCHAR2(100),
    telefono VARCHAR2(20),
    email VARCHAR2(100),
    direccion VARCHAR2(200)
);

CREATE TABLE productos_proveedores (
    id_producto NUMBER NOT NULL,
    id_proveedor NUMBER NOT NULL,
    PRIMARY KEY (id_producto, id_proveedor),
    CONSTRAINT fk_prod FOREIGN KEY (id_producto) REFERENCES productos(id_producto),
    CONSTRAINT fk_prov FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor)
);

CREATE TABLE tiendas (
    id_tienda NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    direccion VARCHAR2(200),
    ciudad VARCHAR2(100),
    telefono VARCHAR2(20)
);

CREATE TABLE inventario_tienda (
    id_tienda NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    stock_actual NUMBER DEFAULT 0,
    stock_reservado NUMBER DEFAULT 0,
    ultima_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_tienda, id_producto),
    CONSTRAINT fk_inv_tienda FOREIGN KEY (id_tienda) REFERENCES tiendas(id_tienda),
    CONSTRAINT fk_inv_prod FOREIGN KEY (id_producto) REFERENCES productos(id_producto)
);

CREATE TABLE clientes (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    dni CHAR(8) UNIQUE NOT NULL,
    email VARCHAR2(100),
    telefono VARCHAR2(20),
    fecha_registro DATE DEFAULT CURRENT_DATE
);

CREATE TABLE empleados (
    id_empleado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellidos VARCHAR2(100) NOT NULL,
    dni CHAR(8) UNIQUE NOT NULL,
    cargo VARCHAR2(50),
    tienda_id NUMBER NOT NULL,
    fecha_ingreso DATE DEFAULT CURRENT_DATE,
    CONSTRAINT fk_emp_tienda FOREIGN KEY (tienda_id) REFERENCES tiendas(id_tienda)
);

-- Añadir gerente en tiendas
ALTER TABLE tiendas
    ADD gerente_id NUMBER
    ADD CONSTRAINT fk_gerente FOREIGN KEY (gerente_id) REFERENCES empleados(id_empleado);

CREATE TABLE ventas (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_venta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    cliente_id NUMBER,
    empleado_id NUMBER,
    tienda_id NUMBER,
    total NUMBER(10,2) DEFAULT 0,
    estado VARCHAR2(20) DEFAULT 'PENDIENTE',
    CONSTRAINT fk_ven_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id_cliente),
    CONSTRAINT fk_ven_empleado FOREIGN KEY (empleado_id) REFERENCES empleados(id_empleado),
    CONSTRAINT fk_ven_tienda FOREIGN KEY (tienda_id) REFERENCES tiendas(id_tienda)
);

CREATE TABLE detalle_venta (
    id_venta NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    subtotal NUMBER(10,2),
    PRIMARY KEY (id_venta, id_producto),
    CONSTRAINT fk_det_venta FOREIGN KEY (id_venta) REFERENCES ventas(id_venta) ON DELETE CASCADE,
    CONSTRAINT fk_det_prod FOREIGN KEY (id_producto) REFERENCES productos(id_producto)
);

CREATE TABLE movimientos_inventario (
    id_movimiento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_movimiento VARCHAR2(50) NOT NULL, 
    id_producto NUMBER NOT NULL,
    cantidad NUMBER NOT NULL,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_mov_prod FOREIGN KEY (id_producto) REFERENCES productos(id_producto),
    CONSTRAINT fk_mov_user FOREIGN KEY (usuario_id) REFERENCES empleados(id_empleado)
);

CREATE TABLE auditoria_precios (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL,
    precio_anterior NUMBER(10,2) NOT NULL,
    precio_nuevo NUMBER(10,2) NOT NULL,
    fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_id NUMBER NOT NULL,
    CONSTRAINT fk_aud_prod FOREIGN KEY (id_producto) REFERENCES productos(id_producto),
    CONSTRAINT fk_aud_user FOREIGN KEY (usuario_id) REFERENCES empleados(id_empleado)
);